#!/bin/bash
#
#
APACHE2=$(dpkg-query -W -f='${Status}' apache2 2>/dev/null | grep -c "ok installed")
if [ $APACHE2 -eq 0 ]
then
        echo "Apache2 paigaldus"
        pause
        apt install apache2 -y

elif [ $APACHE2 -eq 1 ]
then
        echo "Apache2 on paigaldatud"
        pause
        systemctl status apache2
fi
